=== AODtorusan/nifty-gui/src/main/xsd/nifty.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified"
  elementFormDefault="qualified"
  targetNamespace='http://nifty-gui.sourceforge.net/nifty.xsd'
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:nifty="http://nifty-gui.sourceforge.net/nifty.xsd">
  <xs:element name="screen" type="nifty:screenType" />
  <xs:complexType name="elementType" abstract="true">
    <xs:complexContent>
      <xs:extension base="nifty:elementTypeBase">
        <xs:sequence>
          <xs:element name="interact" type="nifty:interactType"
            maxOccurs="1" minOccurs="0">
          </xs:element>
          <xs:element name="hover" type="nifty:elementHoverType"
            maxOccurs="1" minOccurs="0">
          </xs:element>
          <xs:element name="effect" type="nifty:effectsType"
            minOccurs="0" maxOccurs="1">
          </xs:element>
          <xs:element ref="nifty:elementBase" minOccurs="0"
            maxOccurs="unbounded">
          </xs:element>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string"></xs:attribute>
        <xs:attribute name="width" type="nifty:widthType"></xs:attribute>
        <xs:attribute name="height" type="nifty:heightType"></xs:attribute>
        <xs:attribute name="align" type="nifty:alignType"></xs:attribute>
        <xs:attribute name="valign" type="nifty:valignType"></xs:attribute>
        <xs:attribute name="childLayout" type="nifty:layoutType"></xs:attribute>
        <xs:attribute name="childClip" type="xs:boolean"></xs:attribute>
        <xs:attribute name="backgroundImage" type="xs:string"></xs:attribute>
        <xs:attribute name="backgroundColor" type="nifty:colorType"></xs:attribute>
        <xs:attribute name="visibleToMouse" type="xs:boolean"></xs:attribute>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="panelType">
    <xs:complexContent>
      <xs:extension base="nifty:elementType"></xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="imageType">
    <xs:complexContent>
      <xs:extension base="nifty:elementType">
        <xs:attribute type="xs:string" name="filename" use="required" />
        <xs:attribute name="x" type="xs:int" use="optional"></xs:attribute>
        <xs:attribute name="y" type="xs:int" use="optional"></xs:attribute>
        <xs:attribute name="filter" type="xs:boolean" use="optional"></xs:attribute>
        <xs:attribute name="subImageSizeMode">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:enumeration value="scale"></xs:enumeration>
              <xs:enumeration value="resizeHint"></xs:enumeration>
            </xs:restriction>
          </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="resizeHint" type="xs:string"></xs:attribute>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="screenType">
    <xs:sequence>
      <xs:element name="layerGroup" maxOccurs="unbounded"
        minOccurs="0">
        <xs:complexType>
          <xs:attribute name="id" type="xs:string"></xs:attribute>
          <xs:attribute name="alternate" type="xs:string"></xs:attribute>
        </xs:complexType>
      </xs:element>
      <xs:element type="nifty:layerType" name="layer"
        maxOccurs="unbounded" minOccurs="1" />
    </xs:sequence>
    <xs:attribute name="id" type="xs:string"></xs:attribute>
    <xs:attribute name="controller" type="xs:string"></xs:attribute>
    <xs:attribute name="effectGroup" type="xs:string"></xs:attribute>
  </xs:complexType>
  <xs:complexType name="effectType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="name" type="xs:string"></xs:attribute>
        <xs:attribute name="post" type="nifty:postType"></xs:attribute>
        <xs:attribute name="alternateEnable" type="xs:string"></xs:attribute>
        <xs:attribute name="alternateDisable" type="xs:string"></xs:attribute>
        <xs:attribute name="inherit" type="xs:boolean" use="optional"></xs:attribute>
        <xs:anyAttribute namespace="##local" processContents="skip">
        </xs:anyAttribute>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:simpleType name="colorType">
    <xs:restriction base="xs:string">
      <xs:pattern value="#[a-z,0-9]{8,8}"></xs:pattern>
      <xs:pattern value="#[a-z,0-9]{4,4}"></xs:pattern>
      <xs:minLength value="5"></xs:minLength>
      <xs:maxLength value="9"></xs:maxLength>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="layoutType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="vertical"></xs:enumeration>
      <xs:enumeration value="center"></xs:enumeration>
      <xs:enumeration value="absolute"></xs:enumeration>
      <xs:enumeration value="horizontal"></xs:enumeration>
      <xs:enumeration value="overlay"></xs:enumeration>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="directionType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="top"></xs:enumeration>
      <xs:enumeration value="bottom"></xs:enumeration>
      <xs:enumeration value="left"></xs:enumeration>
      <xs:enumeration value="right"></xs:enumeration>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="textType">
    <xs:complexContent>
      <xs:extension base="nifty:elementType">
        <xs:attribute name="text" type="xs:string" use="required"></xs:attribute>
        <xs:attribute name="layout" type="nifty:layoutType"
          use="optional">
        </xs:attribute>
        <xs:attribute name="font" type="xs:string"></xs:attribute>
        <xs:attribute name="color" type="nifty:colorType"></xs:attribute>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="element" type="nifty:elementTypeBase"
    substitutionGroup="nifty:elementBase">
  </xs:element>
  <xs:element name="panel" type="nifty:panelType"
    substitutionGroup="nifty:elementBase">
  </xs:element>
  <xs:element name="text" type="nifty:textType"
    substitutionGroup="nifty:elementBase">
  </xs:element>
  <xs:element name="image" type="nifty:imageType"
    substitutionGroup="nifty:elementBase">
  </xs:element>
  <xs:simpleType name="alignType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="left"></xs:enumeration>
      <xs:enumeration value="center"></xs:enumeration>
      <xs:enumeration value="right"></xs:enumeration>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="widthType">
    <xs:restriction base="xs:string"></xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="heightType">
    <xs:restriction base="xs:string"></xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="valignType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="top"></xs:enumeration>
      <xs:enumeration value="center"></xs:enumeration>
      <xs:enumeration value="bottom"></xs:enumeration>
    </xs:restriction>
  </xs:simpleType>
  <xs:element name="menu" type="nifty:menuType"
    substitutionGroup="nifty:elementBase">
  </xs:element>
  <xs:complexType name="menuType">
    <xs:complexContent>
      <xs:extension base="nifty:elementType">
        <xs:attribute name="font" type="xs:string"></xs:attribute>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="menuItemType">
    <xs:complexContent>
      <xs:extension base="nifty:elementType">
        <xs:attribute name="text" type="xs:string"></xs:attribute>
        <xs:attribute name="color" type="nifty:colorType"></xs:attribute>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="menuItem" type="nifty:menuItemType"
    substitutionGroup="nifty:elementBase">
  </xs:element>
  <xs:complexType name="layerType" block="#all">
    <xs:complexContent>
      <xs:extension base="nifty:panelType"></xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="effectsType">
    <xs:sequence>
      <xs:element name="onStartScreen" type="nifty:effectType"
        maxOccurs="unbounded" minOccurs="0">
      </xs:element>
      <xs:element name="onEndScreen" type="nifty:effectType"
        maxOccurs="unbounded" minOccurs="0">
      </xs:element>
      <xs:element name="onHover" type="nifty:effectType"
        maxOccurs="unbounded" minOccurs="0">
      </xs:element>
      <xs:element name="onClick" type="nifty:effectType"
        maxOccurs="unbounded" minOccurs="0">
      </xs:element>
      <xs:element name="onFocus" type="nifty:effectType"
        maxOccurs="unbounded" minOccurs="0">
      </xs:element>
      <xs:element name="onActive" type="nifty:effectType"
        maxOccurs="unbounded" minOccurs="0">
      </xs:element>
    </xs:sequence>
    <xs:attribute name="effectGroup" type="xs:string"></xs:attribute>
    <xs:attribute name="effectGroupOverride" type="xs:string"></xs:attribute>
  </xs:complexType>
  <xs:element name="nifty" type="nifty:niftyType"></xs:element>
  <xs:complexType name="niftyType">
    <xs:sequence>
      <xs:element name="registerEffect" type="nifty:registerEffectType"
        maxOccurs="unbounded" minOccurs="0">
      </xs:element>
      <xs:element name="registerSound" type="nifty:registerSoundType"
        maxOccurs="unbounded" minOccurs="0">
      </xs:element>
      <xs:element name="registerMusic" type="nifty:registerMusicType"
        maxOccurs="unbounded" minOccurs="0">
      </xs:element>
      <xs:element name="controlDefinition"
        type="nifty:controlDefinition" maxOccurs="unbounded"
        minOccurs="0">
      </xs:element>
      <xs:element name="screen" type="nifty:screenType"
        maxOccurs="unbounded" minOccurs="1">
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="registerEffectType">
    <xs:attribute name="name" type="xs:string"></xs:attribute>
    <xs:attribute name="class" type="xs:string"></xs:attribute>
  </xs:complexType>
  <xs:simpleType name="hoverFalloffType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="none"></xs:enumeration>
      <xs:enumeration value="linear"></xs:enumeration>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="hoverFalloffConstraintType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="none"></xs:enumeration>
      <xs:enumeration value="vertical"></xs:enumeration>
      <xs:enumeration value="horizontal"></xs:enumeration>
      <xs:enumeration value="done"></xs:enumeration>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="postType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="true"></xs:enumeration>
      <xs:enumeration value="false"></xs:enumeration>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="registerSoundType">
    <xs:attribute name="id" type="xs:string"></xs:attribute>
    <xs:attribute name="filename" type="xs:string"></xs:attribute>
  </xs:complexType>
  <xs:complexType name="registerMusicType">
    <xs:attribute name="id" type="xs:string"></xs:attribute>
    <xs:attribute name="filename" type="xs:string"></xs:attribute>
  </xs:complexType>
  <xs:complexType name="controlDefinition">
    <xs:sequence>
      <xs:element ref="nifty:elementBase" maxOccurs="unbounded"
        minOccurs="0">
      </xs:element>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string"></xs:attribute>
    <xs:attribute name="controller" type="xs:string"></xs:attribute>
  </xs:complexType>
  <xs:complexType name="controlType">
    <xs:complexContent>
      <xs:extension base="nifty:elementType">
        <xs:attribute name="name" type="xs:string"></xs:attribute>
        <xs:attribute name="onChange" type="xs:string"></xs:attribute>
        <xs:anyAttribute processContents="skip"
          namespace="##targetNamespace">
        </xs:anyAttribute>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="control" type="nifty:controlType"
    substitutionGroup="nifty:elementBase">
  </xs:element>
  <xs:element name="elementBase" type="nifty:elementTypeBase"></xs:element>
  <xs:complexType name="elementTypeBase"></xs:complexType>
  <xs:complexType name="elementHoverType">
    <xs:attribute name="width" type="nifty:widthType"></xs:attribute>
    <xs:attribute name="height" type="nifty:heightType"></xs:attribute>
    <xs:attribute name="falloffType" type="nifty:hoverFalloffType"></xs:attribute>
    <xs:attribute name="falloffConstraint"
      type="nifty:hoverFalloffConstraintType">
    </xs:attribute>
  </xs:complexType>
  <xs:complexType name="interactType">
    <xs:attribute name="onClick" type="nifty:onClickType"></xs:attribute>
    <xs:attribute name="onClickRepeat" type="nifty:onClickType"></xs:attribute>
    <xs:attribute name="onClickMouseMove" type="nifty:onClickType"></xs:attribute>
    <xs:attribute name="onClickAlternateKey" type="xs:string"></xs:attribute>
  </xs:complexType>
  <xs:simpleType name="onClickType">
    <xs:restriction base="xs:string">
      <xs:pattern value="\w+\((|\w+(,\s*\w+)*)\)"></xs:pattern>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== AODtorusan/nifty-gui/src/main/resources/intro/intro.xml
<?xml version="1.0" encoding="UTF-8"?>
<nifty xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="nifty.xsd">

  <!-- +++++++++++++++++++++++++++++++++++++++ -->
  <!-- register effects we want to use -->
  <!-- +++++++++++++++++++++++++++++++++++++++ -->
  <registerEffect name="imageSize" class="de.lessvoid.nifty.effects.general.ImageSize" />
  <registerEffect name="nop" class="de.lessvoid.nifty.effects.general.Nop" />
  <registerEffect name="fade" class="de.lessvoid.nifty.effects.general.Fade" />
  <registerEffect name="hide" class="de.lessvoid.nifty.effects.general.Hide" />
  <registerEffect name="shake" class="de.lessvoid.nifty.effects.general.Shake" />
  <registerEffect name="playSound" class="de.lessvoid.nifty.effects.general.PlaySound" />
  <registerEffect name="move" class="de.lessvoid.nifty.effects.general.Move" />
  <registerEffect name="pulsate" class="de.lessvoid.nifty.effects.general.Pulsate" />
  <registerEffect name="pulsateHover" class="de.lessvoid.nifty.effects.hover.Pulsate" />
  
  <!-- +++++++++++++++++++++++++++++++++++++++ -->
  <!-- register sounds -->
  <!-- +++++++++++++++++++++++++++++++++++++++ -->
  <registerSound id="intro" filename="intro/intro.wav" />

  <!-- +++++++++++++++++++++++++++++++++++++++ -->
  <!-- intro screen -->
  <!-- +++++++++++++++++++++++++++++++++++++++ -->
  <screen id="start" controller="de.lessvoid.nifty.examples.intro.Splash">
    <layer id="background" childLayout="center">
      <panel id="panel" height="100%" width="100%" backgroundColor="#ffff">
        <effect>
          <onStartScreen name="fade" startColor="#000f" endColor="#ffff" length="100" post="false"/>
          <onEndScreen name="fade" startColor="#ffff" endColor="#000f" length="500" post="false"/>
        </effect>
      </panel>
    </layer>
    <layer id="logo" childLayout="center">
      <panel id="panel" height="60%" childLayout="center">
        <image id="image" filename="intro/nifty.png" align="center">
          <effect>
            <onStartScreen name="playSound" sound="intro" length="3300"/>
            <onStartScreen name="fade" startColor="#fff0" endColor="#ffff" length="1700" />
            <onStartScreen name="imageSize" factor="0.5" startSize="0.5" endSize="1.0" length="1700" />
            <onStartScreen name="shake" length="4200" startDelay="500" global="false" />
            <onEndScreen name="move" mode="toPosition" targetElement="image2" length="500"/>
          </effect>
        </image>
      </panel>
    </layer>
    <layer id="logo2" childLayout="vertical" visible="false">
      <panel id="panel2" height="30%" childLayout="center">
        <image id="image2" filename="intro/nifty.png" align="center"/>
      </panel>
    </layer>
  </screen>

  <!-- +++++++++++++++++++++++++++++++++++++++ -->
  <!-- menu screen -->
  <!-- +++++++++++++++++++++++++++++++++++++++ -->
  <screen id="menu" controller="de.lessvoid.nifty.examples.intro.Menu">
    <layer id="top" childLayout="vertical" backgroundColor="#393939ff">
      <effect>
        <onStartScreen name="fade" startColor="#000f" endColor="#393939ff" length="500"/>
        <onEndScreen name="fade" startColor="#393939ff" endColor="#000000ff" length="500"/>
      </effect>
      <panel id="panel" height="30%" childLayout="center">
        <image id="image" filename="intro/nifty.png" align="center">
          <effect>
            <onEndScreen name="fade" startColor="#ffff" endColor="#0000" length="500" />
          </effect>
        </image>
      </panel>
    </layer>
    <layer id="menu" childLayout="center">
      <menu id="mainMenu" font="menu.fnt" childLayout="vertical" align="center">
        <effect>
          <onStartScreen name="hide" length="500" inherit="true" startDelay="1000"/>
          <onStartScreen name="fade" startColor="#fff0" endColor="#ffff" length="1000" startDelay="500" inherit="true"/>
          <onEndScreen name="fade" startColor="#ffff" endColor="#fff0" length="500" inherit="true"/>
        </effect>
        <menuItem id="helloWorld" text="Hello World" align="center">
          <interact onClick="helloWorld()"/>
          <hover width="200%" falloffConstraint="horizontal"/>
          <effect>
            <onHover name="pulsateHover" hoverWidth="200%" width="200%" period="500" startColor="#3c000000" endColor="#ff7c00ff" timeType="infinite" cycle="false"/>
          </effect>
        </menuItem>
        <menuItem id="textfield" text="Textfield Example" align="center">
          <interact onClick="textField()"/>
          <hover width="200%" falloffConstraint="horizontal"/>
          <effect>
            <onHover name="pulsateHover" hoverWidth="200%" width="200%" period="500" startColor="#3c000000" endColor="#ff7c00ff" timeType="infinite" cycle="false"/>
          </effect>
        </menuItem>
        <menuItem id="quit" text="Quit" align="center">
          <interact onClick="quit()"/>
          <hover width="200%" falloffConstraint="horizontal"/>
          <effect>
            <onHover name="pulsateHover" hoverWidth="200%" width="200%" period="500" startColor="#3c000000" endColor="#ff7c00ff" timeType="infinite" cycle="false"/>
          </effect>
        </menuItem>
      </menu>
    </layer>
    <layer id="example" childLayout="absolute">
      <image x="550" y="170" filename="intro/examples.png" align="center">
        <effect>
          <onStartScreen name="move" direction="right" mode="in" length="800" />
          <onStartScreen name="fade" startColor="#0000" endColor="#ffff" length="800" />
          <onEndScreen name="move" direction="right" mode="out" length="800" />
          <onEndScreen name="fade" startColor="#ffff" endColor="#0000" length="800" />
        </effect>
      </image>
    </layer>
  </screen>

  <!-- +++++++++++++++++++++++++++++++++++++++ -->
  <!-- outro screen -->
  <!-- +++++++++++++++++++++++++++++++++++++++ -->
  <screen id="outro" controller="de.lessvoid.nifty.examples.intro.Outro">
    <layer id="logo" childLayout="center">
      <image id="image" filename="intro/nifty.png" align="center">
        <effect>
          <onStartScreen name="fade" startColor="#fff0" endColor="#ffff" length="1000" />
          <onStartScreen name="imageSize" startSize="0.0" endSize="1.0" length="1000" />
          <onEndScreen name="fade" startColor="#ffff" endColor="#fff0" length="1000" />
          <onEndScreen name="imageSize" startSize="1.0" endSize="2.0" length="1000" />
        </effect>
      </image>
    </layer>
  </screen>
  
</nifty>

=== AODtorusan/nifty-gui/src/main/resources/data/ui/multiOverlay.xml
<?xml version="1.0" encoding="UTF-8"?>
<nifty xmlns="http://nifty-gui.sourceforge.net/nifty.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://nifty-gui.sourceforge.net/nifty.xsd http://nifty-gui.sourceforge.net/nifty.xsd">
  <!-- we don't have to use a style for this but this makes it easier -->
  <style id="shake">
    <effect>
      <onCustom name="shake" global="false" length="1000" />
    </effect>
  </style>

  <!-- one simple screen for this example -->
  <screen id="screen2" controller="de.lessvoid.nifty.examples.slick.niftyoverlay.examples.TestStateTwo$Controller">

    <!-- this layer comes straight from the hello world example -->
    <layer id="layer" childLayout="center">
      <panel id="panel" height="30%" width="25%" align="center" valign="center" backgroundColor="#f06c" childLayout="center" visibleToMouse="true">
        <interact onClick="quit()"/>
        <effect>
          <onStartScreen name="move" mode="in" direction="top" length="600" startDelay="0" inherit="true"/>
          <onEndScreen name="move" mode="out" direction="bottom" length="600" startDelay="0" inherit="true"/>
          <onHover name="pulsate" scaleFactor="0.008" startColor="#f600" endColor="#ffff" post="true"/>
        </effect>
        <text id="text" font="aurulent-sans-17.fnt" color="#000f" text="... and this is Nifty on top&#13;&#10;... click this with mouse to quit" align="center" valign="center" />
      </panel>
    </layer>

    <!-- this layer shows three boxes that shake when triggered from java -->
    <layer id="boxes" childLayout="vertical">
   	  <text id="text" font="aurulent-sans-17.fnt" color="#aaaf" text="Nifty screen2" align="right" valign="bottom" />
      <panel height="80%"/>
      <panel height="*" childLayout="center" backgroundColor="#555c">
        <effect>
          <onStartScreen name="move" mode="in" direction="left" length="600" startDelay="0" inherit="true"/>
          <onEndScreen name="move" mode="out" direction="left" length="600" startDelay="0" inherit="true"/>
        </effect>
        <panel width="90%" height="70%" align="center" valign="center" childLayout="horizontal">
          <panel id="red" width="9%" height="70%" backgroundColor="#f00f" valign="center" style="shake" />
          <panel id="green" width="9%" height="70%" backgroundColor="#0f0f" valign="center" style="shake" />
          <panel id="blue" width="9%" height="70%" backgroundColor="#00ff" valign="center" style="shake" />
        </panel>
      </panel>
    </layer>

    <!-- this layer shows a image in the upper left corner which is toggled from java -->
    <layer childLayout="absolute">
      <image id="inventar" x="940px" y="20px" filename="data/ui/icon1.png" align="center" valign="bottom">
        <effect>
          <onCustom name="imageSize" startSize="1.7" endSize="2.0" length="150" />
        </effect>
      </image>
    </layer>
  </screen>



  <!-- second screen for this example -->
  <screen id="screen1" controller="de.lessvoid.nifty.examples.slick.niftyoverlay.examples.TestStateOne$Controller">

    <!-- this layer comes straight from the hello world example -->
    <layer id="layer" childLayout="center">
      <panel id="panel" height="10%" width="35%" align="center" valign="center" backgroundColor="#f60c" childLayout="center" visibleToMouse="true">
        <interact onClick="quit()"/>
        <effect>
          <onStartScreen name="move" mode="in" direction="top" length="600" startDelay="0" inherit="true"/>
          <onEndScreen name="move" mode="out" direction="bottom" length="600" startDelay="0" inherit="true"/>
          <onHover name="pulsate" scaleFactor="0.008" startColor="#f600" endColor="#ffff" post="true"/>
        </effect>
        <text id="text" font="aurulent-sans-17.fnt" color="#000f" text="... and this is Nifty on top&#13;&#10;... click this with mouse to quit" align="center" valign="center" />
      </panel>
    </layer>

    <!-- this layer shows three boxes that shake when triggered from java -->
    <layer id="boxes" childLayout="vertical">
   	  <text id="text" font="aurulent-sans-17.fnt" color="#aaaf" text="Nifty screen1" align="right" valign="bottom" />
      <panel height="80%"/>
      <panel height="*" childLayout="center" backgroundColor="#888c">
        <effect>
          <onStartScreen name="move" mode="in" direction="left" length="600" startDelay="0" inherit="true"/>
          <onEndScreen name="move" mode="out" direction="left" length="600" startDelay="0" inherit="true"/>
        </effect>
        <panel width="90%" height="70%" align="center" valign="center" childLayout="horizontal">
          <panel id="red" width="9%" height="70%" backgroundColor="#f00f" valign="center" style="shake" />
          <panel id="green" width="9%" height="70%" backgroundColor="#0f0f" valign="center" style="shake" />
          <panel id="blue" width="9%" height="70%" backgroundColor="#00ff" valign="center" style="shake" />
        </panel>
      </panel>
    </layer>

    <!-- this layer shows a image in the upper left corner which is toggled from java -->
    <layer childLayout="absolute">
      <image id="inventar" x="940px" y="20px" filename="data/ui/icon1.png" align="center" valign="bottom">
        <effect>
          <onCustom name="imageSize" startSize="1.7" endSize="1.0" length="150" />
        </effect>
      </image>
    </layer>
  </screen>


</nifty>
